server:
  port: 8762

eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: true  #true代表注册到Eureka列表
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/  #指向服务注册中心的地址
  server:
    enable-self-preservation: false  # 关闭自我保护机制
spring:
  application:
    name: cloud-eureka-eureka-1